/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gaussiterative;

import main.java.gaussiterative.GaussJacobiIterative;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        GaussJacobiIterative gauss = new GaussJacobiIterative();
        
        System.out.println(gauss);
       
    }
}
