/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gaussiterative;

import main.java.gaussiterative.GaussJacobiIterative;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        double[] solution = { 12, 3, 4 };
        double[] result = { 12, 3, 4 };
       boolean check = GaussJacobiIterative.isSolution(result, solution);
       System.out.println(check);
    }
}
