/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gaussiterative;

import main.java.gaussiterative.GaussJacobiIterative;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        GaussJacobiIterative gauss = new GaussJacobiIterative();
        double[][] matrix = { { 5, 1, 1 }, { 3, 4, 1 }, { 3, 3, 6 } };
        double[] result = { 5, 6, 0 };
        gauss.setMatrix(matrix);
        gauss.setResult(result);
        System.out.println(gauss);

    }
}
